int ctr, ctr1, first, **impl_primi_ReC, s, r;
char** d_Emin, **b_Emin, ** Emin_new, **min_new, **implicanti, **impl_primi, **bin_impl;
_Bool Controlla_Valori(int, int, int*);
double power(unsigned int);
_Bool strcomp(int, int, char**);
char** mtrxcpy(int, int, char**, _Bool); 
char** Bin(int, int, int*);
void Stampa_var (int);
void Scambia(char*, char*, int);
int N_uni (int, int, char**);
void Raggruppa_min (char**, int, int, char**);
int N_gruppi(int, int, char**);
void Stampa_min (char**, int, int, char**);
_Bool int_cmp(int, int, int*);
void Crea_impl(int, int);
void Crea_impl_bin( int, int, int);
_Bool Confronta_min(int*, int);
_Bool Semplifica_bit(int, int, int); 
int impl_len (int, char**);
int N_impl (int, char**);
int* atoiz(char**, int);
void Copri_tab (char**, int, int);
void Stampa_tab(char** , int , int , int*);
char** Tab_Copertura(int, char**, int, int*);
int int_cmp2(int, int, int*);
_Bool Implicanti_Primi (int, int, char**, int*);
void Stampa_tab_primi();
void Colonne();
void Righe();
int Implicanti_tab(int , int , char** , int*);
void Stampa_Fine (_Bool, int, int, int*, _Bool, int);
void Free_mtrx(int, char**);
 